//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_Rental_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public Car()
        {
            this.T_Reservation = new HashSet<T_Reservation>();
            this.T_Rent = new HashSet<T_Rent>();
        }
    
        public int CarId { get; set; }
        public string Brand { get; set; }
        public string Type { get; set; }
        public Nullable<int> Stock { get; set; }
        public string Model { get; set; }
        public Nullable<int> SeatQuantity { get; set; }
        public string FuelType { get; set; }
        public Nullable<int> Mileage { get; set; }
        public Nullable<double> DailyPrice { get; set; }
        public string ImgSrc { get; set; }
    
        public virtual ICollection<T_Reservation> T_Reservation { get; set; }
        public virtual ICollection<T_Rent> T_Rent { get; set; }
    }
}
