//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_Rental_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Billing
    {
        public int BillId { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public Nullable<int> RentId { get; set; }
    
        public virtual T_Rent T_Rent { get; set; }
    }
}
