//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_Rental_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Reservation
    {
        public T_Reservation()
        {
            this.T_Rent = new HashSet<T_Rent>();
        }
    
        public int ReservationId { get; set; }
        public Nullable<System.DateTime> ReservationDate { get; set; }
        public Nullable<System.DateTime> PickupDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<int> CarId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual ICollection<T_Rent> T_Rent { get; set; }
        public virtual T_Users T_Users { get; set; }
        public virtual Car Car { get; set; }
    }
}
