//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_Rental_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Rent
    {
        public T_Rent()
        {
            this.T_Billing = new HashSet<T_Billing>();
        }
    
        public int RentId { get; set; }
        public Nullable<int> TotalRentDay { get; set; }
        public Nullable<double> DailyRentFee { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<double> Refund { get; set; }
        public Nullable<int> CarId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ReservationId { get; set; }
    
        public virtual ICollection<T_Billing> T_Billing { get; set; }
        public virtual T_Reservation T_Reservation { get; set; }
        public virtual T_Users T_Users { get; set; }
        public virtual Car Car { get; set; }
    }
}
